### ISSUE TITLE
Requesting to be member of community manager team

### ISSUE THREAD

**Issue by eneskemalergin** [open-source-society/help#5]
Hello All,

My name is Enes Kemal Ergin. I am a senior computer science student with software engineering major and bioinformatics passion. I spend most of my time doing academic research and teaching.

I loved what you guys started, I believe our future education system will benefit from this and other similar actions. That's why I would like to be a part of this society. I personally started doing similar actions by making online curriculum for our small bioinformatics group.  

I would like to start new department :) Bioinformatics or Computational Biology for the open source society.

 my email and my website is on my github page...

**Comment by ericdouglas** [comment]
Hey @eneskemalergin ! I'm glad that you want to help us!

I created the [Bioinformatics repository](https://github.com/open-source-society/bioinformatics), sent an invite to you join us in the organization and promoted you to be the **team maintainer** of that repository, so you can add and remove member to the _Bioinformatics Team_.

Any doubts just send a message to us :smile: 

Thanks again! :tada: :pray:

**Comment by ericdouglas** [comment]
@eneskemalergin sorry, I forgot to add the bioinformatics repo to the Bioinformatics Team. Now you can send/accept modifications. :sweat_smile:

**Comment by papyGCG** [comment]
Hi all 
I hope you are doing great.
My name is Bakary, I recently graduated from my pharmacy studies.
I have much interest in bioinformatics. I’m a learner through online resources like MOOCs. I read these articles (http://journals.plos.org/ploscompbiol/article/related?id=10.1371%2Fjournal.pcbi.1002632
http://journals.plos.org/ploscompbiol/article?id=info:doi/10.1371/journal.pcbi.1003662)
sometimes ago and I think it’s great for online learning.
Also I started studying computer science in an online University.
I’m interested in working on open source projects mainly to build some experience. I think I have some programming background, and enough biology background. I’ll really be please to participate in any project. 
Hope to join you !
Thanks 
https://www.linkedin.com/in/bakary-n-tji-diallo-49479347

**Comment by ericdouglas** [comment]
@papyGCG thanks for your interest in help us!

I think you can talk with @eneskemalergin and you both could discuss the Bioinformatics curriculum and build it together.

That will be a good start point, IMO. @eneskemalergin can invite you to be part of the Bioinformatics Team. :smile:

**Comment by ericdouglas** [comment]
Hey @papyGCG we now have a chat for the Bioinformatics course. If you are interested in help in this project you can just talk with @eneskemalergin and the other guys there :smile:
