### ISSUE TITLE
game development track

### ISSUE THREAD

**Issue by mseyne** [open-source-society/help#6]
Hello,

As I see the development of others track than computer science, I feel I could propose to come back to help and focus on my current interests, development of a game development curriculum. I think it would be great to share it through ossu.

It would be first a HTML5 game dev track with javascript mostly using free web ressources from everywhere (not much moocs only, but articles, videos, etc..).

Hope to join back the project of a free and open university. :smile:

**Comment by ericdouglas** [comment]
Hey @mseyne ! I'm really happy to see you again :smile: 

We can create a path for this topic for sure, just tell me the name of the repository that you think fits well in your proposal and I'll create it and give to you the necessary permissions to start.

**Comment by mseyne** [comment]
Great @ericdouglas  :)
I will take some time to prepare a first draft as template and come back to you.
For the name : "game-development" sound good :smile:

**Comment by ericdouglas** [comment]
@mseyne [done](https://github.com/open-source-society/game-development) :white_check_mark: 

You already have permission to manage the repository :smile:

Thank you for your interest in help us! :pray:
